<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

<?php foreach ($pages as $page):?>
    <url>
        <!-- Page: <?php echo $page->name_en;?> -->
        <loc>https://mercedes-benz-mauritius.com/<?php echo $page->slug_en;?></loc>
        <lastmod><?php echo date('Y-m-d').'T'.date('H:i:s');?>+00:00</lastmod>
    </url>
<?php endforeach;?>

<?php foreach ($vehicle_models as $model):?>
    <url>
        <!-- Model: <?php echo $model->model;?> -->
        <loc>https://mercedes-benz-mauritius.com/models/<?php echo $model->slug;?></loc>
        <lastmod><?php echo date('Y-m-d').'T'.date('H:i:s');?>+00:00</lastmod>
    </url>
<?php endforeach;?>

</urlset>
<!-- Generated by <?php echo $_SESSION['authenticated_user']->name;?><<?php echo $_SESSION['authenticated_user']->email;?>>, Netsiteweaver Ltd on <?php echo date('Y-m-d H:i:s');?> -->